server:
  port: 8081
  servlet:
    context-path: /lsso-resource-server

security:
  oauth2:
    resource:
      id: service
      userInfoUri: http://localhost:8083/users/userinfo

spring:
  datasource:
    username: sa
    url: jdbc:h2:mem:testdb;DB_CLOSE_ON_EXIT=FALSE;
  jpa:
    defer-datasource-initialization: true
    open-in-view: false

logging.level.org.springframework.security: DEBUG
