server:
  port: 8081
  servlet:
    context-path: /resource

security.oauth2.resource.jwt.key-value: 123456

#security.oauth2.resource.jwt.key-value: |
#  -----BEGIN PUBLIC KEY-----
#  MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQDdlatRjRjogo3WojgGHFHYLugd
#  UWAY9iR3fy4arWNA1KoS8kVw33cJibXr8bvwUAUparCwlvdbH6dvEOfou0/gCFQs
#  HUfQrSDv+MuSUMAe8jzKE4qW+jK+xQU9a03GUnKHkkle+Q0pX/g6jXZ7r1/xAK5D
#  o2kQ+X5xK9cipRgEKwIDAQAB
#  -----END PUBLIC KEY-----

spring:
  datasource:
    username: sa
    url: jdbc:h2:mem:testdb;DB_CLOSE_ON_EXIT=FALSE;
  jpa:
    defer-datasource-initialization: true
    open-in-view: false

logging.level.org.springframework.security: TRACE
