server:
  port: 8083

#spring:
#  security:
#    user:
#      # user / pass
#      name: user
#      password: "{bcrypt}$2a$04$kqRvgmJBlWZQQ2c9NT9IH.ZhxFY07Y2xE73vmLHxBq2hNTvGvUc5m"
#    oauth2:
#      authorizationserver:
#        client:
#          client:
#            registration:
#              # client / secret
#              client-id: "client"
#              client-secret: "{bcrypt}$2a$10$s2onvDh4DiiVClBGgbYN6eLwXHFPl4YATKpAAmoK1Rx7Fdzd3KCqm"
#              client-authentication-methods:
#                - "client_secret_basic"
#              authorization-grant-types:
#                - "authorization_code"
#                - "refresh_token"
#              redirect-uris:
#                - "http://localhost:8082/lsso-client/login/oauth2/code/spring"
#              scopes:
#                - "openid"
#                - "read"
#                - "write"
#            require-authorization-consent: false
