security.oauth2.client.client-id: client
security.oauth2.client.client-secret: secret
security.oauth2.authorization.checkTokenAccess: isAuthenticated()

# logging.level.org.springframework.security: DEBUG
