server:
  port: 8083

spring:
  security:
    user:
      # user/pass
      name: user
      password: pass

security:
  oauth2:
    client:
      client-id: client
      client-secret: secret
      scope:
        - read
        - write
      authorized-grant-types:
        - client_credentials
        - password
    authorization:
      check-token-access: isAuthenticated()

# logging.level.org.springframework.security=DEBUG
