server:
  port: 8081
  servlet:
    context-path: /lsso-resource-server

security:
  oauth2:
    client:
      clientId: client
      clientSecret: secret
    resource:
      token-info-uri: http://localhost:8083/oauth/check_token
      jwk:
        key-set-uri: http://localhost:8083/endpoint/jwks.json


spring:
  datasource:
    username: sa
    url: jdbc:h2:mem:testdb;DB_CLOSE_ON_EXIT=FALSE;
  jpa:
    defer-datasource-initialization: true
    open-in-view: false

logging.level.org.springframework.security: DEBUG
